name: Continuous integration and Image deployment of Bobapp's frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-package-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout bobapp source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: front/package-lock.json


      - name: Install dependencies
        run: npm ci
        working-directory: front
      - name: Run tests and get coverage
        run: npm run test:ci
        working-directory: front
      - name: Build
        run: npm run build
        working-directory: front
         
      - name: Upload test coverage report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage report
          path: |
            front/coverage
      - name: Publish Front Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
              files: |
                front/test_results/test-results.xml
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front-sfy:latest